version: '3.9'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python create_superuser.py && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - .env:/code/.env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env


  db:
    image: postgres:16
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: sh -c 'pg_isready -U "$$POSTGRES_USER"'
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
